### ISSUE TITLE
8teenboy images

### ISSUE THREAD

**Issue by paladin732** [acvigue/pgma#1]
Hi! Thanks for making the changes with 8teenboy and getting it up and running.

Quick question: The first image downloaded is always the 8teenboy logo (see attached). Any way to fix that?
<img width="1467" alt="Screen Shot 2019-07-20 at 6 29 29 PM" src="https://user-images.githubusercontent.com/52991727/61585886-5e3cfd00-ab1c-11e9-9d83-72c50647d85e.png">

**Comment by acvigue** [comment]
ya. i'll fix it right now, I have that issue too. Oh, I forgot to mention, the model images are temporarily uploaded to a server I host (neural.vigue.me) that gets the faces and crops correctly. Are you OK with that? I should probably add an opt-out switch in the prefs tho.

**Comment by paladin732** [comment]
Yea, I couldn't care less about that :). The fact this works is awesome and saves so much time. Just wish dates would work, but following the URLs you use, dates are not even there.

**Comment by acvigue** [comment]
Do you have dates on the members-only pages?


------ Original Message ------

**Comment by paladin732** [comment]
Yes, they are on the member only pages.

**Comment by acvigue** [comment]
Same link?

**Comment by acvigue** [comment]
issue fixed in commit https://github.com/acvigue/pgma/commit/1ed57b382f409126b5ff003036af54610f4092a2

**Comment by paladin732** [comment]
Not quite:

https://www.8teenboy.com/members/video/3893/making-it.html . URL is inaccessible when not logged in though, so I don't think there is a way to use it.

**Comment by acvigue** [comment]
If you close your browser without explicitly logging out of 8TB, do you have to login again to view that link?

I'll see if I can have the agent imitate a logged in user.

**Comment by paladin732** [comment]
ahhh, looks like I'm wrong. I just tried logging in and see no dates. Digging deeper:

Looks like the OLD plugin was assigning dates to them when searching for them as helix. Not quite sure how that happened, but the dates they had do look roughly correct

**Comment by acvigue** [comment]
could you go here: https://www.gayeroticvideoindex.com/search.php
and select "titles for words" & "containing". put the exact full title in the search box.
if this works, I can get the date, and label the actors as bottom / top.

**Comment by paladin732** [comment]
Looks like it works by searching for the actors
https://www.gayeroticvideoindex.com/S/9/116589.html for instance has "jack philips solo session"

**Comment by acvigue** [comment]
ok. I'll write a script that will scrape that site.

**Comment by acvigue** [comment]
added in commit https://github.com/acvigue/pgma/commit/1cba47f5204415b744d8117e6ba89796e1915a4a

**Comment by paladin732** [comment]
Works great, of 72 videos 66 now have dates.

Thanks!

**Comment by acvigue** [comment]
You're welcome. Any reason why the other 8 have no dates?

**Comment by acvigue** [comment]
Fixed. GEVI scene matching has improved. Run `git pull` to update
