### ISSUE TITLE
Latest Waybig Bundle: Improved Poster Art retrieval: Issue raised by J-KTZ

### ISSUE THREAD

**Issue by JPH71** [acvigue/pgma#10]
Hi J-KTZ

This fixeed bundle should hopefully sort out your corbinfisher videos.

remember plain apostrophe's in your titles and not the curved ones

[WayBig.bundle.zip](https://github.com/acvigue/pgma/files/4079773/WayBig.bundle.zip)

**Comment by j-ktz** [comment]
Got it, thanks!!!

**Comment by acvigue** [comment]
will upload, but i am not 100% focused on this project right now, sadly. Progress would move much faster in this repository if pull requests were used. An easy way to get started with them is a desktop app like Github Desktop, and there are many guides online. Most new users would not look in the issues to find updated bundles, they would just download the latest release.

**Comment by acvigue** [comment]
merged.

**Comment by acvigue** [comment]
Thank you very much for the contribution!
