### ISSUE TITLE
Adding boys-pissing and mydirtiestfantasy 

### ISSUE THREAD

**Issue by Thisismygithubname1** [acvigue/pgma#6]
What would it take to add these twink fetish sites. I was going to sign up for a short account to get some videos, but I want to make sure I can easily add them to plex.

Looks like it would supply all the info added. There are search functions on both sites that shows all the details when not logged in.

**Comment by acvigue** [comment]
you can either use XPath expressions to scrape the videos, or you can use a client-side JS script that converts it into a XML file for use by the XML agent

**Comment by Thisismygithubname1** [comment]
What would it take to get some help with getting these ones created?
