### ISSUE TITLE
WayBig agent not matching all the time

### ISSUE THREAD

**Issue by CodyBerenson** [acvigue/pgma#7]
Specifically for clips, the WayBig agent is TERRIFIC...but also hit or miss, and I can't pinpoint a pattern. It seems that commas are an issue, and sometimes single quotes.  TimTales had about 25% failure rate.  Bromo 50%.  CockyBoys 15%.  Can't get it to work with Lucas Entertainment.   

I've included several Waybig examples that work and don't for your trouble-shooting. As you can see, it isn't visually consistent why some titles work and others do not. lol. 

Sometimes clips with "," work, sometime not. "&"    "."     "!"   all seem to be troublesome.   Sometimes the studios have ":" in the title but of course that can't be part of the filename...

Thanks!

Works:
(Bromo) - Man Meat (Rico Fatale Barebacks Alex Morgan) (2018).mp4
(Bromo) - Blake Ryder Fucks Brendan Patrick in ‘Tied And Teased’ (2019).mp4
(Bromo) - Darin Silvers Fucks Daxx Carter in ‘Cellmates, Part 2’ (2019).mp4
(CockyBoys) - ‘Hole Whisperer’ Max Adonis Fucks Wesley Woods RAW (2019)
(CockyBoys) - Küper Ryan Fucks Nico Leon (2019)

Does not:
(Bromo) - Electric Sex, Part 1 (Rikk York Fucks Jay Austin) (2018).mp4
(Bromo) - Eddie Danger Fucks Eli Hunter in ‘Raw Tow Service, Part 3’ (2019).mp4
(Bromo) - Zane Stone Fucks Draven Navarro in ‘Lords of RAW-Dog, Part 2’ (2018).mp4
(CockyBoys) - Austin Wolf Fucks Sean Ford in ‘A Man and His Boy 2’ (2019).mp4
(CockyBoys) - Blake Mitchell Fucks Hayden Brier in ‘The Best Days of Our Lives’ (2019)
(CockyBoys) - Ricky Roman & Küper Ryan Flip-Fuck [Webcam Show Bonus Scene] (2019).mp4

I'm happy to help test, etc., just explain what you need. 

Whatever can be done would be REALLY appreciated!  Thanks so much.

**Comment by acvigue** [comment]
just a note. i have seen this and will look more into it for tomorrow. I have a few ideas that might work

**Comment by CodyBerenson** [comment]
All of the terrific updates that Jason's made to the WayBig Bundle allows this issue to be closed.  Thanks Jason and Aiden for merging.
